# Generated by Django 3.0.5 on 2020-06-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200609_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together=set(),
        ),
    ]
