# Generated by Django 3.0.5 on 2020-06-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200609_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together={('title', 'slug')},
        ),
    ]
