# Generated by Django 3.0.5 on 2020-06-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('shopping_cart', '0003_cartitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
