# Generated by Django 3.0.5 on 2020-06-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('shopping_cart', '0006_auto_20200608_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='listings.Post'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
