# Generated by Django 3.0.5 on 2020-06-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0007_auto_20200609_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
