# Generated by Django 3.0.5 on 2020-05-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200527_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
